### PR TITLE
Add testing framework

### PR DESCRIPTION
**Pull request by radford-for-smpte**

### CODE REVIEW

**Comment by palemieux** [comment]
I am getting:

```
  Registries
    1) "before all" hook in "Registries"
    2) "after all" hook in "Registries"


  0 passing (1s)
  2 failing

  1) Registries
       "before all" hook in "Registries":
     TypeError: Object.values(...).map(...).flat is not a function
      at schemaFiles.reduce (lib\upstream.js:58:63)

  2) Registries
       "after all" hook in "Registries":
     TypeError: Cannot read property 'close' of undefined
      at Context.after (test\server.js:46:34)
```

Is there a minimal node version? I am running `v10.13.0`.

**Comment by palemieux** [comment]
What about using `"https://github.com/ISDCF/registries/"` if `REGISTRY_REPOSITORY` is undefined?

**Comment by radford-for-smpte** [comment]
> I am getting:
> 
> ```
>   Registries
>     1) "before all" hook in "Registries"
>     2) "after all" hook in "Registries"
> 
> 
>   0 passing (1s)
>   2 failing
> 
>   1) Registries
>        "before all" hook in "Registries":
>      TypeError: Object.values(...).map(...).flat is not a function
>       at schemaFiles.reduce (lib\upstream.js:58:63)
> 
>   2) Registries
>        "after all" hook in "Registries":
>      TypeError: Cannot read property 'close' of undefined
>       at Context.after (test\server.js:46:34)
> ```
> 
> Is there a minimal node version? I am running `v10.13.0`.

Yes, v12. I should add an `engine` definition to `package.json`.

**Comment by palemieux** [comment]
Tests pass with `v12.18.2`

**Comment by radford-for-smpte** [comment]
> What about using `"https://github.com/ISDCF/registries/"` if `REGISTRY_REPOSITORY` is undefined?

Created #8

**Pull request merged**
